/* 
**  mod_cdnalizer.c -- Apache sample cdnalizer module
**  [Autogenerated via ``apxs -n cdnalizer -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_cdnalizer.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /cdnalizer in as follows:
**
**    #   apache2.conf
**    LoadModule cdnalizer_module modules/mod_cdnalizer.so
**    <Location /cdnalizer>
**    SetHandler cdnalizer
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /cdnalizer and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/cdnalizer 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_cdnalizer.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

static const char cdnalizer_filter_name[] = "CDNALIZER";

/*
static const command_rec cdnalizer_filter_cmds[] = {
    AP_INIT_RAW_ARGS("CDNRewriteRule", cmd_cdnrewriterule, NULL, OR_FILEINFO,
                     "an URL-applied regexp-pattern and a substitution (cdn) URL");
}
*/

struct State {
    apr_bucket_brigade* tmpbb;
};

static apr_status_t cdnalize_out_filter(ap_filter_t *filter, apr_bucket_brigade *bb)
{
    // Don't pass empty brigodes down the line
    if (APR_BRIGADE_EMPTY(bb)) {
        return APR_SUCCESS;
    }
    struct State* state = filter->ctx;
    if (state == NULL) {
        filter->ctx = state = apr_palloc(filter->r->pool, sizeof *state);
        state->tmpbb = apr_brigade_create(filter->r->pool, filter->c->bucket_alloc);
    }
    // Get the first bucket
    apr_bucket *bucket = APR_BRIGADE_FIRST(bb);
    const char *data;
    apr_size_t length;
    while (bucket != APR_BRIGADE_SENTINEL(bb)) {
        apr_status_t status;
        // Get the data
        status = apr_bucket_read(bucket, &data, &length, APR_BLOCK_READ);
        bucket = APR_BUCKET_NEXT(bucket);
    }
    return ap_pass_brigade(filter->next, bb);
}

static void cdnalizer_register_hooks(apr_pool_t *p)
{
    ap_register_output_filter(cdnalizer_filter_name, cdnalize_out_filter, NULL,
                              AP_FTYPE_CONTENT_SET);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA cdnalizer_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    /*cdnalizer_filter_cmds, /* table of config file commands       */
    NULL,
    cdnalizer_register_hooks  /* register hooks                      */
};

